language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../lab-7-arrlist
  - make -j
  - cd ./bin/
  - ./test_arrlist
notifications:
  email: false
